//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.487.0.
namespace BCFmarkup
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Header", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Header
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Collection<HeaderFile> _file;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("File")]
        public Collection<HeaderFile> File
        {
            get
            {
                return this._file;
            }
            private set
            {
                this._file = value;
            }
        }
        
        public Header()
        {
            this._file = new Collection<HeaderFile>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("HeaderFile", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HeaderFile : IFileAttributes
    {
        
        [System.Xml.Serialization.XmlElementAttribute("Filename")]
        public string Filename { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Date", DataType="dateTime")]
        public System.DateTime Date { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Reference")]
        public string Reference { get; set; }
        
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(22)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(22)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9,A-Z,a-z,_$]*")]
        [System.Xml.Serialization.XmlAttributeAttribute("IfcProject")]
        public string IfcProject { get; set; }
        
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(22)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(22)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9,A-Z,a-z,_$]*")]
        [System.Xml.Serialization.XmlAttributeAttribute("IfcSpatialStructureElement")]
        public string IfcSpatialStructureElement { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _isExternal = true;
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        [System.Xml.Serialization.XmlAttributeAttribute("isExternal")]
        public bool IsExternal
        {
            get
            {
                return this._isExternal;
            }
            set
            {
                this._isExternal = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    public partial interface IFileAttributes
    {
        
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(22)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(22)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9,A-Z,a-z,_$]*")]
        string IfcProject
        {
            get;
            set;
        }
        
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(22)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(22)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9,A-Z,a-z,_$]*")]
        string IfcSpatialStructureElement
        {
            get;
            set;
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        bool IsExternal
        {
            get;
            set;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ViewPoint", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ViewPoint
    {
        
        [System.Xml.Serialization.XmlElementAttribute("Viewpoint")]
        public string Viewpoint { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Snapshot")]
        public string Snapshot { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Index")]
        public int Index { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndexSpecified { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Guid")]
        public string Guid { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BimSnippet", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BimSnippet
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Reference")]
        public string Reference { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ReferenceSchema")]
        public string ReferenceSchema { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("SnippetType")]
        public string SnippetType { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _isExternal = false;
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlAttributeAttribute("isExternal")]
        public bool IsExternal
        {
            get
            {
                return this._isExternal;
            }
            set
            {
                this._isExternal = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Topic", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Topic
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Collection<string> _referenceLink;
        
        [System.Xml.Serialization.XmlElementAttribute("ReferenceLink")]
        public Collection<string> ReferenceLink
        {
            get
            {
                return this._referenceLink;
            }
            private set
            {
                this._referenceLink = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReferenceLinkSpecified
        {
            get
            {
                return (this.ReferenceLink.Count != 0);
            }
        }
        
        public Topic()
        {
            this._referenceLink = new Collection<string>();
            this._labels = new Collection<string>();
            this._documentReference = new Collection<TopicDocumentReference>();
            this._relatedTopic = new Collection<TopicRelatedTopic>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Title")]
        public string Title { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Priority")]
        public string Priority { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Index")]
        public int Index { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndexSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Collection<string> _labels;
        
        [System.Xml.Serialization.XmlElementAttribute("Labels")]
        public Collection<string> Labels
        {
            get
            {
                return this._labels;
            }
            private set
            {
                this._labels = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LabelsSpecified
        {
            get
            {
                return (this.Labels.Count != 0);
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("CreationDate", DataType="dateTime")]
        public System.DateTime CreationDate { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("CreationAuthor")]
        public string CreationAuthor { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ModifiedDate", DataType="dateTime")]
        public System.DateTime ModifiedDate { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModifiedDateSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ModifiedAuthor")]
        public string ModifiedAuthor { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("DueDate", DataType="dateTime")]
        public System.DateTime DueDate { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DueDateSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("AssignedTo")]
        public string AssignedTo { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Stage")]
        public string Stage { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public string Description { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("BimSnippet")]
        public BimSnippet BimSnippet { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Collection<TopicDocumentReference> _documentReference;
        
        [System.Xml.Serialization.XmlElementAttribute("DocumentReference")]
        public Collection<TopicDocumentReference> DocumentReference
        {
            get
            {
                return this._documentReference;
            }
            private set
            {
                this._documentReference = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentReferenceSpecified
        {
            get
            {
                return (this.DocumentReference.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Collection<TopicRelatedTopic> _relatedTopic;
        
        [System.Xml.Serialization.XmlElementAttribute("RelatedTopic")]
        public Collection<TopicRelatedTopic> RelatedTopic
        {
            get
            {
                return this._relatedTopic;
            }
            private set
            {
                this._relatedTopic = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RelatedTopicSpecified
        {
            get
            {
                return (this.RelatedTopic.Count != 0);
            }
        }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Guid")]
        public string Guid { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("TopicType")]
        public string TopicType { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("TopicStatus")]
        public string TopicStatus { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TopicDocumentReference", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TopicDocumentReference : IDocumentReference
    {
        
        [System.Xml.Serialization.XmlElementAttribute("ReferencedDocument")]
        public string ReferencedDocument { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public string Description { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}")]
        [System.Xml.Serialization.XmlAttributeAttribute("Guid")]
        public string Guid { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _isExternal = false;
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlAttributeAttribute("isExternal")]
        public bool IsExternal
        {
            get
            {
                return this._isExternal;
            }
            set
            {
                this._isExternal = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    public partial interface IDocumentReference
    {
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}")]
        string Guid
        {
            get;
            set;
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        bool IsExternal
        {
            get;
            set;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TopicRelatedTopic", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TopicRelatedTopic
    {
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Guid")]
        public string Guid { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Comment", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Comment
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Date", DataType="dateTime")]
        public System.DateTime Date { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Author")]
        public string Author { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Comment")]
        public string CommentProperty { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Viewpoint")]
        public CommentViewpoint Viewpoint { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ModifiedDate", DataType="dateTime")]
        public System.DateTime ModifiedDate { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModifiedDateSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ModifiedAuthor")]
        public string ModifiedAuthor { get; set; }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Guid")]
        public string Guid { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CommentViewpoint", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CommentViewpoint
    {
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Guid")]
        public string Guid { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Markup", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Markup", Namespace="")]
    public partial class Markup
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Collection<HeaderFile> _header;
        
        [System.Xml.Serialization.XmlArrayAttribute("Header")]
        [System.Xml.Serialization.XmlArrayItemAttribute("File")]
        public Collection<HeaderFile> Header
        {
            get
            {
                return this._header;
            }
            private set
            {
                this._header = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeaderSpecified
        {
            get
            {
                return (this.Header.Count != 0);
            }
        }
        
        public Markup()
        {
            this._header = new Collection<HeaderFile>();
            this._comments = new Collection<Comment>();
            this._viewpoints = new Collection<ViewPoint>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Topic")]
        public Topic Topic { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Collection<Comment> _comments;
        
        [System.Xml.Serialization.XmlElementAttribute("Comments")]
        public Collection<Comment> Comments
        {
            get
            {
                return this._comments;
            }
            private set
            {
                this._comments = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CommentsSpecified
        {
            get
            {
                return (this.Comments.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Collection<ViewPoint> _viewpoints;
        
        [System.Xml.Serialization.XmlElementAttribute("Viewpoints")]
        public Collection<ViewPoint> Viewpoints
        {
            get
            {
                return this._viewpoints;
            }
            private set
            {
                this._viewpoints = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ViewpointsSpecified
        {
            get
            {
                return (this.Viewpoints.Count != 0);
            }
        }
    }
}
