//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.490.0.
namespace BCFmarkup
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("Header", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class Header
    {
        
        [XmlIgnoreAttribute()]
        private Collection<HeaderFile> _file;
        
        [RequiredAttribute()]
        [XmlElementAttribute("File")]
        public Collection<HeaderFile> File
        {
            get
            {
                return this._file;
            }
            private set
            {
                this._file = value;
            }
        }
        
        public Header()
        {
            this._file = new Collection<HeaderFile>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("HeaderFile", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class HeaderFile : IFileAttributes
    {
        
        [XmlElementAttribute("Filename")]
        public String Filename { get; set; }
        
        [XmlElementAttribute("Date", DataType="dateTime")]
        public DateTime Date { get; set; }
        
        [XmlIgnoreAttribute()]
        public bool DateSpecified { get; set; }
        
        [XmlElementAttribute("Reference")]
        public String Reference { get; set; }
        
        [MinLengthAttribute(22)]
        [MaxLengthAttribute(22)]
        [RegularExpressionAttribute("[0-9,A-Z,a-z,_$]*")]
        [XmlAttributeAttribute("IfcProject")]
        public String IfcProject { get; set; }
        
        [MinLengthAttribute(22)]
        [MaxLengthAttribute(22)]
        [RegularExpressionAttribute("[0-9,A-Z,a-z,_$]*")]
        [XmlAttributeAttribute("IfcSpatialStructureElement")]
        public String IfcSpatialStructureElement { get; set; }
        
        [XmlIgnoreAttribute()]
        private Boolean _isExternal = true;
        
        [DefaultValueAttribute(true)]
        [XmlAttributeAttribute("isExternal")]
        public Boolean IsExternal
        {
            get
            {
                return this._isExternal;
            }
            set
            {
                this._isExternal = value;
            }
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    public partial interface IFileAttributes
    {
        
        [MinLengthAttribute(22)]
        [MaxLengthAttribute(22)]
        [RegularExpressionAttribute("[0-9,A-Z,a-z,_$]*")]
        String IfcProject
        {
            get;
            set;
        }
        
        [MinLengthAttribute(22)]
        [MaxLengthAttribute(22)]
        [RegularExpressionAttribute("[0-9,A-Z,a-z,_$]*")]
        String IfcSpatialStructureElement
        {
            get;
            set;
        }
        
        [DefaultValueAttribute(true)]
        Boolean IsExternal
        {
            get;
            set;
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ViewPoint", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ViewPoint
    {
        
        [XmlElementAttribute("Viewpoint")]
        public String Viewpoint { get; set; }
        
        [XmlElementAttribute("Snapshot")]
        public String Snapshot { get; set; }
        
        [XmlElementAttribute("Index")]
        public Int32 Index { get; set; }
        
        [XmlIgnoreAttribute()]
        public bool IndexSpecified { get; set; }
        
        [RegularExpressionAttribute("[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}")]
        [RequiredAttribute()]
        [XmlAttributeAttribute("Guid")]
        public String Guid { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("BimSnippet", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class BimSnippet
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("Reference")]
        public String Reference { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("ReferenceSchema")]
        public String ReferenceSchema { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("SnippetType")]
        public String SnippetType { get; set; }
        
        [XmlIgnoreAttribute()]
        private Boolean _isExternal = false;
        
        [DefaultValueAttribute(false)]
        [XmlAttributeAttribute("isExternal")]
        public Boolean IsExternal
        {
            get
            {
                return this._isExternal;
            }
            set
            {
                this._isExternal = value;
            }
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("Topic", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class Topic
    {
        
        [XmlIgnoreAttribute()]
        private Collection<String> _referenceLink;
        
        [XmlElementAttribute("ReferenceLink")]
        public Collection<String> ReferenceLink
        {
            get
            {
                return this._referenceLink;
            }
            private set
            {
                this._referenceLink = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public Boolean ReferenceLinkSpecified
        {
            get
            {
                return (this.ReferenceLink.Count != 0);
            }
        }
        
        public Topic()
        {
            this._referenceLink = new Collection<String>();
            this._labels = new Collection<String>();
            this._documentReference = new Collection<TopicDocumentReference>();
            this._relatedTopic = new Collection<TopicRelatedTopic>();
        }
        
        [RequiredAttribute()]
        [XmlElementAttribute("Title")]
        public String Title { get; set; }
        
        [XmlElementAttribute("Priority")]
        public String Priority { get; set; }
        
        [XmlElementAttribute("Index")]
        public Int32 Index { get; set; }
        
        [XmlIgnoreAttribute()]
        public bool IndexSpecified { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<String> _labels;
        
        [XmlElementAttribute("Labels")]
        public Collection<String> Labels
        {
            get
            {
                return this._labels;
            }
            private set
            {
                this._labels = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public Boolean LabelsSpecified
        {
            get
            {
                return (this.Labels.Count != 0);
            }
        }
        
        [RequiredAttribute()]
        [XmlElementAttribute("CreationDate", DataType="dateTime")]
        public DateTime CreationDate { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("CreationAuthor")]
        public String CreationAuthor { get; set; }
        
        [XmlElementAttribute("ModifiedDate", DataType="dateTime")]
        public DateTime ModifiedDate { get; set; }
        
        [XmlIgnoreAttribute()]
        public bool ModifiedDateSpecified { get; set; }
        
        [XmlElementAttribute("ModifiedAuthor")]
        public String ModifiedAuthor { get; set; }
        
        [XmlElementAttribute("DueDate", DataType="dateTime")]
        public DateTime DueDate { get; set; }
        
        [XmlIgnoreAttribute()]
        public bool DueDateSpecified { get; set; }
        
        [XmlElementAttribute("AssignedTo")]
        public String AssignedTo { get; set; }
        
        [XmlElementAttribute("Stage")]
        public String Stage { get; set; }
        
        [XmlElementAttribute("Description")]
        public String Description { get; set; }
        
        [XmlElementAttribute("BimSnippet")]
        public BimSnippet BimSnippet { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<TopicDocumentReference> _documentReference;
        
        [XmlElementAttribute("DocumentReference")]
        public Collection<TopicDocumentReference> DocumentReference
        {
            get
            {
                return this._documentReference;
            }
            private set
            {
                this._documentReference = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public Boolean DocumentReferenceSpecified
        {
            get
            {
                return (this.DocumentReference.Count != 0);
            }
        }
        
        [XmlIgnoreAttribute()]
        private Collection<TopicRelatedTopic> _relatedTopic;
        
        [XmlElementAttribute("RelatedTopic")]
        public Collection<TopicRelatedTopic> RelatedTopic
        {
            get
            {
                return this._relatedTopic;
            }
            private set
            {
                this._relatedTopic = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public Boolean RelatedTopicSpecified
        {
            get
            {
                return (this.RelatedTopic.Count != 0);
            }
        }
        
        [RegularExpressionAttribute("[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}")]
        [RequiredAttribute()]
        [XmlAttributeAttribute("Guid")]
        public String Guid { get; set; }
        
        [XmlAttributeAttribute("TopicType")]
        public String TopicType { get; set; }
        
        [XmlAttributeAttribute("TopicStatus")]
        public String TopicStatus { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("TopicDocumentReference", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class TopicDocumentReference : IDocumentReference
    {
        
        [XmlElementAttribute("ReferencedDocument")]
        public String ReferencedDocument { get; set; }
        
        [XmlElementAttribute("Description")]
        public String Description { get; set; }
        
        [RegularExpressionAttribute("[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}")]
        [XmlAttributeAttribute("Guid")]
        public String Guid { get; set; }
        
        [XmlIgnoreAttribute()]
        private Boolean _isExternal = false;
        
        [DefaultValueAttribute(false)]
        [XmlAttributeAttribute("isExternal")]
        public Boolean IsExternal
        {
            get
            {
                return this._isExternal;
            }
            set
            {
                this._isExternal = value;
            }
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    public partial interface IDocumentReference
    {
        
        [RegularExpressionAttribute("[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}")]
        String Guid
        {
            get;
            set;
        }
        
        [DefaultValueAttribute(false)]
        Boolean IsExternal
        {
            get;
            set;
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("TopicRelatedTopic", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class TopicRelatedTopic
    {
        
        [RegularExpressionAttribute("[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}")]
        [RequiredAttribute()]
        [XmlAttributeAttribute("Guid")]
        public String Guid { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("Comment", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class Comment
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("Date", DataType="dateTime")]
        public DateTime Date { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("Author")]
        public String Author { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("Comment")]
        public String CommentProperty { get; set; }
        
        [XmlElementAttribute("Viewpoint")]
        public CommentViewpoint Viewpoint { get; set; }
        
        [XmlElementAttribute("ModifiedDate", DataType="dateTime")]
        public DateTime ModifiedDate { get; set; }
        
        [XmlIgnoreAttribute()]
        public bool ModifiedDateSpecified { get; set; }
        
        [XmlElementAttribute("ModifiedAuthor")]
        public String ModifiedAuthor { get; set; }
        
        [RegularExpressionAttribute("[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}")]
        [RequiredAttribute()]
        [XmlAttributeAttribute("Guid")]
        public String Guid { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("CommentViewpoint", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class CommentViewpoint
    {
        
        [RegularExpressionAttribute("[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}")]
        [RequiredAttribute()]
        [XmlAttributeAttribute("Guid")]
        public String Guid { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("Markup", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("Markup", Namespace="")]
    public partial class Markup
    {
        
        [XmlIgnoreAttribute()]
        private Collection<HeaderFile> _header;
        
        [XmlArrayAttribute("Header")]
        [XmlArrayItemAttribute("File")]
        public Collection<HeaderFile> Header
        {
            get
            {
                return this._header;
            }
            private set
            {
                this._header = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public Boolean HeaderSpecified
        {
            get
            {
                return (this.Header.Count != 0);
            }
        }
        
        public Markup()
        {
            this._header = new Collection<HeaderFile>();
            this._comment = new Collection<Comment>();
            this._viewpoints = new Collection<ViewPoint>();
        }
        
        [RequiredAttribute()]
        [XmlElementAttribute("Topic")]
        public Topic Topic { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<Comment> _comment;
        
        [XmlElementAttribute("Comment")]
        public Collection<Comment> Comment
        {
            get
            {
                return this._comment;
            }
            private set
            {
                this._comment = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public Boolean CommentSpecified
        {
            get
            {
                return (this.Comment.Count != 0);
            }
        }
        
        [XmlIgnoreAttribute()]
        private Collection<ViewPoint> _viewpoints;
        
        [XmlElementAttribute("Viewpoints")]
        public Collection<ViewPoint> Viewpoints
        {
            get
            {
                return this._viewpoints;
            }
            private set
            {
                this._viewpoints = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public Boolean ViewpointsSpecified
        {
            get
            {
                return (this.Viewpoints.Count != 0);
            }
        }
    }
}
