//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.490.0.
namespace BCFproject
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("Project", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class Project
    {
        
        [XmlElementAttribute("Name")]
        public String Name { get; set; }
        
        [RequiredAttribute()]
        [XmlAttributeAttribute("ProjectId")]
        public String ProjectId { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ProjectExtension", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("ProjectExtension", Namespace="")]
    public partial class ProjectExtension
    {
        
        [XmlElementAttribute("Project")]
        public Project Project { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("ExtensionSchema")]
        public String ExtensionSchema { get; set; }
    }
}
