//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.490.0.
namespace BCFvisinfo
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("OrthogonalCamera", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class OrthogonalCamera
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("CameraViewPoint")]
        public Point CameraViewPoint { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("CameraDirection")]
        public Direction CameraDirection { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("CameraUpVector")]
        public Direction CameraUpVector { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("ViewToWorldScale")]
        public Double ViewToWorldScale { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("Point", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class Point
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("X")]
        public Double X { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("Y")]
        public Double Y { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("Z")]
        public Double Z { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("Direction", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class Direction
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("X")]
        public Double X { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("Y")]
        public Double Y { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("Z")]
        public Double Z { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("PerspectiveCamera", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class PerspectiveCamera
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("CameraViewPoint")]
        public Point CameraViewPoint { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("CameraDirection")]
        public Direction CameraDirection { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("CameraUpVector")]
        public Direction CameraUpVector { get; set; }
        
        [RangeAttribute(typeof(double), "45", "60")]
        [RequiredAttribute()]
        [XmlElementAttribute("FieldOfView")]
        public Double FieldOfView { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("Components", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class Components
    {
        
        [XmlElementAttribute("ViewSetupHints")]
        public ViewSetupHints ViewSetupHints { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<Component> _selection;
        
        [XmlArrayAttribute("Selection")]
        [XmlArrayItemAttribute("Component")]
        public Collection<Component> Selection
        {
            get
            {
                return this._selection;
            }
            private set
            {
                this._selection = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public Boolean SelectionSpecified
        {
            get
            {
                return (this.Selection.Count != 0);
            }
        }
        
        public Components()
        {
            this._selection = new Collection<Component>();
            this._coloring = new Collection<ComponentColoringColor>();
        }
        
        [RequiredAttribute()]
        [XmlElementAttribute("Visibility")]
        public ComponentVisibility Visibility { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<ComponentColoringColor> _coloring;
        
        [XmlArrayAttribute("Coloring")]
        [XmlArrayItemAttribute("Color")]
        public Collection<ComponentColoringColor> Coloring
        {
            get
            {
                return this._coloring;
            }
            private set
            {
                this._coloring = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public Boolean ColoringSpecified
        {
            get
            {
                return (this.Coloring.Count != 0);
            }
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ViewSetupHints", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ViewSetupHints
    {
        
        [XmlAttributeAttribute("SpacesVisible")]
        public Boolean SpacesVisible { get; set; }
        
        [XmlIgnoreAttribute()]
        public bool SpacesVisibleSpecified { get; set; }
        
        [XmlAttributeAttribute("SpaceBoundariesVisible")]
        public Boolean SpaceBoundariesVisible { get; set; }
        
        [XmlIgnoreAttribute()]
        public bool SpaceBoundariesVisibleSpecified { get; set; }
        
        [XmlAttributeAttribute("OpeningsVisible")]
        public Boolean OpeningsVisible { get; set; }
        
        [XmlIgnoreAttribute()]
        public bool OpeningsVisibleSpecified { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ComponentSelection", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ComponentSelection
    {
        
        [XmlIgnoreAttribute()]
        private Collection<Component> _component;
        
        [RequiredAttribute()]
        [XmlElementAttribute("Component")]
        public Collection<Component> Component
        {
            get
            {
                return this._component;
            }
            private set
            {
                this._component = value;
            }
        }
        
        public ComponentSelection()
        {
            this._component = new Collection<Component>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("Component", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class Component
    {
        
        [XmlElementAttribute("OriginatingSystem")]
        public String OriginatingSystem { get; set; }
        
        [XmlElementAttribute("AuthoringToolId")]
        public String AuthoringToolId { get; set; }
        
        [MinLengthAttribute(22)]
        [MaxLengthAttribute(22)]
        [RegularExpressionAttribute("[0-9,A-Z,a-z,_$]*")]
        [XmlAttributeAttribute("IfcGuid", Namespace="", Form=XmlSchemaForm.Qualified)]
        public String IfcGuid { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ComponentVisibility", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ComponentVisibility
    {
        
        [XmlIgnoreAttribute()]
        private Collection<Component> _exceptions;
        
        [XmlArrayAttribute("Exceptions")]
        [XmlArrayItemAttribute("Component")]
        public Collection<Component> Exceptions
        {
            get
            {
                return this._exceptions;
            }
            private set
            {
                this._exceptions = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public Boolean ExceptionsSpecified
        {
            get
            {
                return (this.Exceptions.Count != 0);
            }
        }
        
        public ComponentVisibility()
        {
            this._exceptions = new Collection<Component>();
        }
        
        [XmlAttributeAttribute("DefaultVisibility")]
        public Boolean DefaultVisibility { get; set; }
        
        [XmlIgnoreAttribute()]
        public bool DefaultVisibilitySpecified { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ComponentVisibilityExceptions", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ComponentVisibilityExceptions
    {
        
        [XmlIgnoreAttribute()]
        private Collection<Component> _component;
        
        [RequiredAttribute()]
        [XmlElementAttribute("Component")]
        public Collection<Component> Component
        {
            get
            {
                return this._component;
            }
            private set
            {
                this._component = value;
            }
        }
        
        public ComponentVisibilityExceptions()
        {
            this._component = new Collection<Component>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ComponentColoring", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ComponentColoring
    {
        
        [XmlIgnoreAttribute()]
        private Collection<ComponentColoringColor> _color;
        
        [RequiredAttribute()]
        [XmlElementAttribute("Color")]
        public Collection<ComponentColoringColor> Color
        {
            get
            {
                return this._color;
            }
            private set
            {
                this._color = value;
            }
        }
        
        public ComponentColoring()
        {
            this._color = new Collection<ComponentColoringColor>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ComponentColoringColor", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ComponentColoringColor
    {
        
        [XmlIgnoreAttribute()]
        private Collection<Component> _component;
        
        [RequiredAttribute()]
        [XmlElementAttribute("Component")]
        public Collection<Component> Component
        {
            get
            {
                return this._component;
            }
            private set
            {
                this._component = value;
            }
        }
        
        public ComponentColoringColor()
        {
            this._component = new Collection<Component>();
        }
        
        [RegularExpressionAttribute("[0-9,A-F]{6}([0-9,A-F]{2})?")]
        [XmlAttributeAttribute("Color", Namespace="", Form=XmlSchemaForm.Qualified)]
        public String Color { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("Line", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class Line
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("StartPoint")]
        public Point StartPoint { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("EndPoint")]
        public Point EndPoint { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("ClippingPlane", Namespace="")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class ClippingPlane
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("Location")]
        public Point Location { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("Direction")]
        public Direction Direction { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("BitmapFormat", Namespace="")]
    public enum BitmapFormat
    {
        
        PNG,
        
        JPG,
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("VisualizationInfo", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("VisualizationInfo", Namespace="")]
    public partial class VisualizationInfo
    {
        
        [XmlElementAttribute("Components")]
        public Components Components { get; set; }
        
        [XmlElementAttribute("OrthogonalCamera")]
        public OrthogonalCamera OrthogonalCamera { get; set; }
        
        [XmlElementAttribute("PerspectiveCamera")]
        public PerspectiveCamera PerspectiveCamera { get; set; }
        
        [XmlIgnoreAttribute()]
        private Collection<Line> _lines;
        
        [XmlArrayAttribute("Lines")]
        [XmlArrayItemAttribute("Line")]
        public Collection<Line> Lines
        {
            get
            {
                return this._lines;
            }
            private set
            {
                this._lines = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public Boolean LinesSpecified
        {
            get
            {
                return (this.Lines.Count != 0);
            }
        }
        
        public VisualizationInfo()
        {
            this._lines = new Collection<Line>();
            this._clippingPlanes = new Collection<ClippingPlane>();
            this._bitmap = new Collection<VisualizationInfoBitmap>();
        }
        
        [XmlIgnoreAttribute()]
        private Collection<ClippingPlane> _clippingPlanes;
        
        [XmlArrayAttribute("ClippingPlanes")]
        [XmlArrayItemAttribute("ClippingPlane")]
        public Collection<ClippingPlane> ClippingPlanes
        {
            get
            {
                return this._clippingPlanes;
            }
            private set
            {
                this._clippingPlanes = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public Boolean ClippingPlanesSpecified
        {
            get
            {
                return (this.ClippingPlanes.Count != 0);
            }
        }
        
        [XmlIgnoreAttribute()]
        private Collection<VisualizationInfoBitmap> _bitmap;
        
        [XmlElementAttribute("Bitmap")]
        public Collection<VisualizationInfoBitmap> Bitmap
        {
            get
            {
                return this._bitmap;
            }
            private set
            {
                this._bitmap = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public Boolean BitmapSpecified
        {
            get
            {
                return (this.Bitmap.Count != 0);
            }
        }
        
        [RegularExpressionAttribute("[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}")]
        [RequiredAttribute()]
        [XmlAttributeAttribute("Guid")]
        public String Guid { get; set; }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("VisualizationInfoLines", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class VisualizationInfoLines
    {
        
        [XmlIgnoreAttribute()]
        private Collection<Line> _line;
        
        [RequiredAttribute()]
        [XmlElementAttribute("Line")]
        public Collection<Line> Line
        {
            get
            {
                return this._line;
            }
            private set
            {
                this._line = value;
            }
        }
        
        public VisualizationInfoLines()
        {
            this._line = new Collection<Line>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("VisualizationInfoClippingPlanes", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class VisualizationInfoClippingPlanes
    {
        
        [XmlIgnoreAttribute()]
        private Collection<ClippingPlane> _clippingPlane;
        
        [XmlElementAttribute("ClippingPlane")]
        public Collection<ClippingPlane> ClippingPlane
        {
            get
            {
                return this._clippingPlane;
            }
            private set
            {
                this._clippingPlane = value;
            }
        }
        
        [XmlIgnoreAttribute()]
        public Boolean ClippingPlaneSpecified
        {
            get
            {
                return (this.ClippingPlane.Count != 0);
            }
        }
        
        public VisualizationInfoClippingPlanes()
        {
            this._clippingPlane = new Collection<ClippingPlane>();
        }
    }
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("VisualizationInfoBitmap", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    public partial class VisualizationInfoBitmap
    {
        
        [RequiredAttribute()]
        [XmlElementAttribute("Bitmap")]
        public BitmapFormat Bitmap { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("Reference")]
        public String Reference { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("Location")]
        public Point Location { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("Normal")]
        public Direction Normal { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("Up")]
        public Direction Up { get; set; }
        
        [RequiredAttribute()]
        [XmlElementAttribute("Height")]
        public Double Height { get; set; }
    }
}
