//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.487.0.
namespace BCFvisinfo
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("OrthogonalCamera", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrthogonalCamera
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("CameraViewPoint")]
        public Point CameraViewPoint { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("CameraDirection")]
        public Direction CameraDirection { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("CameraUpVector")]
        public Direction CameraUpVector { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ViewToWorldScale")]
        public double ViewToWorldScale { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Point", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Point
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("X")]
        public double X { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Y")]
        public double Y { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Z")]
        public double Z { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Direction", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Direction
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("X")]
        public double X { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Y")]
        public double Y { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Z")]
        public double Z { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PerspectiveCamera", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PerspectiveCamera
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("CameraViewPoint")]
        public Point CameraViewPoint { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("CameraDirection")]
        public Direction CameraDirection { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("CameraUpVector")]
        public Direction CameraUpVector { get; set; }
        
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(double), "45", "60")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("FieldOfView")]
        public double FieldOfView { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Components", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Components
    {
        
        [System.Xml.Serialization.XmlElementAttribute("ViewSetupHints")]
        public ViewSetupHints ViewSetupHints { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Collection<Component> _selection;
        
        [System.Xml.Serialization.XmlArrayAttribute("Selection")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Component")]
        public Collection<Component> Selection
        {
            get
            {
                return this._selection;
            }
            private set
            {
                this._selection = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SelectionSpecified
        {
            get
            {
                return (this.Selection.Count != 0);
            }
        }
        
        public Components()
        {
            this._selection = new Collection<Component>();
            this._coloring = new Collection<ComponentColoringColor>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Visibility")]
        public ComponentVisibility Visibility { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Collection<ComponentColoringColor> _coloring;
        
        [System.Xml.Serialization.XmlArrayAttribute("Coloring")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Color")]
        public Collection<ComponentColoringColor> Coloring
        {
            get
            {
                return this._coloring;
            }
            private set
            {
                this._coloring = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ColoringSpecified
        {
            get
            {
                return (this.Coloring.Count != 0);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ViewSetupHints", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ViewSetupHints
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("SpacesVisible")]
        public bool SpacesVisible { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SpacesVisibleSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("SpaceBoundariesVisible")]
        public bool SpaceBoundariesVisible { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SpaceBoundariesVisibleSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("OpeningsVisible")]
        public bool OpeningsVisible { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OpeningsVisibleSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ComponentSelection", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComponentSelection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Collection<Component> _component;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Component")]
        public Collection<Component> Component
        {
            get
            {
                return this._component;
            }
            private set
            {
                this._component = value;
            }
        }
        
        public ComponentSelection()
        {
            this._component = new Collection<Component>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Component", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Component
    {
        
        [System.Xml.Serialization.XmlElementAttribute("OriginatingSystem")]
        public string OriginatingSystem { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("AuthoringToolId")]
        public string AuthoringToolId { get; set; }
        
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(22)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(22)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9,A-Z,a-z,_$]*")]
        [System.Xml.Serialization.XmlAttributeAttribute("IfcGuid", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string IfcGuid { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ComponentVisibility", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComponentVisibility
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Collection<Component> _exceptions;
        
        [System.Xml.Serialization.XmlArrayAttribute("Exceptions")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Component")]
        public Collection<Component> Exceptions
        {
            get
            {
                return this._exceptions;
            }
            private set
            {
                this._exceptions = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExceptionsSpecified
        {
            get
            {
                return (this.Exceptions.Count != 0);
            }
        }
        
        public ComponentVisibility()
        {
            this._exceptions = new Collection<Component>();
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("DefaultVisibility")]
        public bool DefaultVisibility { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DefaultVisibilitySpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ComponentVisibilityExceptions", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComponentVisibilityExceptions
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Collection<Component> _component;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Component")]
        public Collection<Component> Component
        {
            get
            {
                return this._component;
            }
            private set
            {
                this._component = value;
            }
        }
        
        public ComponentVisibilityExceptions()
        {
            this._component = new Collection<Component>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ComponentColoring", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComponentColoring
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Collection<ComponentColoringColor> _color;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Color")]
        public Collection<ComponentColoringColor> Color
        {
            get
            {
                return this._color;
            }
            private set
            {
                this._color = value;
            }
        }
        
        public ComponentColoring()
        {
            this._color = new Collection<ComponentColoringColor>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ComponentColoringColor", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComponentColoringColor
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Collection<Component> _component;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Component")]
        public Collection<Component> Component
        {
            get
            {
                return this._component;
            }
            private set
            {
                this._component = value;
            }
        }
        
        public ComponentColoringColor()
        {
            this._component = new Collection<Component>();
        }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9,A-F]{6}([0-9,A-F]{2})?")]
        [System.Xml.Serialization.XmlAttributeAttribute("Color", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Color { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Line", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Line
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("StartPoint")]
        public Point StartPoint { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("EndPoint")]
        public Point EndPoint { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ClippingPlane", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ClippingPlane
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Location")]
        public Point Location { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Direction")]
        public Direction Direction { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BitmapFormat", Namespace="")]
    public enum BitmapFormat
    {
        
        PNG,
        
        JPG,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VisualizationInfo", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("VisualizationInfo", Namespace="")]
    public partial class VisualizationInfo
    {
        
        [System.Xml.Serialization.XmlElementAttribute("Components")]
        public Components Components { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("OrthogonalCamera")]
        public OrthogonalCamera OrthogonalCamera { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("PerspectiveCamera")]
        public PerspectiveCamera PerspectiveCamera { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Collection<Line> _lines;
        
        [System.Xml.Serialization.XmlArrayAttribute("Lines")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Line")]
        public Collection<Line> Lines
        {
            get
            {
                return this._lines;
            }
            private set
            {
                this._lines = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LinesSpecified
        {
            get
            {
                return (this.Lines.Count != 0);
            }
        }
        
        public VisualizationInfo()
        {
            this._lines = new Collection<Line>();
            this._clippingPlanes = new Collection<ClippingPlane>();
            this._bitmap = new Collection<VisualizationInfoBitmap>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Collection<ClippingPlane> _clippingPlanes;
        
        [System.Xml.Serialization.XmlArrayAttribute("ClippingPlanes")]
        [System.Xml.Serialization.XmlArrayItemAttribute("ClippingPlane")]
        public Collection<ClippingPlane> ClippingPlanes
        {
            get
            {
                return this._clippingPlanes;
            }
            private set
            {
                this._clippingPlanes = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClippingPlanesSpecified
        {
            get
            {
                return (this.ClippingPlanes.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Collection<VisualizationInfoBitmap> _bitmap;
        
        [System.Xml.Serialization.XmlElementAttribute("Bitmap")]
        public Collection<VisualizationInfoBitmap> Bitmap
        {
            get
            {
                return this._bitmap;
            }
            private set
            {
                this._bitmap = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BitmapSpecified
        {
            get
            {
                return (this.Bitmap.Count != 0);
            }
        }
        
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Guid")]
        public string Guid { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VisualizationInfoLines", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VisualizationInfoLines
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Collection<Line> _line;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Line")]
        public Collection<Line> Line
        {
            get
            {
                return this._line;
            }
            private set
            {
                this._line = value;
            }
        }
        
        public VisualizationInfoLines()
        {
            this._line = new Collection<Line>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VisualizationInfoClippingPlanes", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VisualizationInfoClippingPlanes
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private Collection<ClippingPlane> _clippingPlane;
        
        [System.Xml.Serialization.XmlElementAttribute("ClippingPlane")]
        public Collection<ClippingPlane> ClippingPlane
        {
            get
            {
                return this._clippingPlane;
            }
            private set
            {
                this._clippingPlane = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClippingPlaneSpecified
        {
            get
            {
                return (this.ClippingPlane.Count != 0);
            }
        }
        
        public VisualizationInfoClippingPlanes()
        {
            this._clippingPlane = new Collection<ClippingPlane>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.487.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VisualizationInfoBitmap", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VisualizationInfoBitmap
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Bitmap")]
        public BitmapFormat Bitmap { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Reference")]
        public string Reference { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Location")]
        public Point Location { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Normal")]
        public Direction Normal { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Up")]
        public Direction Up { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Height")]
        public double Height { get; set; }
    }
}
