//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.490.0.
namespace BCFversion
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.490.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("Version", Namespace="", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("Version", Namespace="")]
    public partial class Version
    {
        
        [XmlElementAttribute("DetailedVersion")]
        public String DetailedVersion { get; set; }
        
        [XmlAttributeAttribute("VersionId")]
        public String VersionId { get; set; }
    }
}
